apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: sample
  template:
    metadata:
      labels:
        component: sample
    spec:
      containers:
      - name: sample
        image: isuruherath22923/spring-boot-hello-world-lolc:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lolcapp1
spec:
  type: NodePort
  selector:
    component: sample
  ports:
    - port: 8080
      targetPort: 8080